apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectd-back
  labels:
    app: projectd-back
  namespace: projectd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: projectd-back
  template:
    metadata:
      labels:
        app: projectd-back
    spec:
      containers:
      - name: projectd-back
        image: skreet2k/projectd-back:1.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: MongoDbConfig__ConnectionString
          value: mongodb://root:A4hPcRbtE8@mongodb.default.svc.cluster.local:27017/
        - name: GameConfiguration__TicksToSpawn
          value: "20"
        - name: GameConfiguration__FeatureConfiguration__InitSpeed
          value: "20"
        - name: GameConfiguration__MillisecondsToTick
          value: "100"    
        - name: GameConfiguration__WaveConfiguration__WaveSpeedModifier
          value: "0.1"    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectd-front
  labels:
    app: projectd-front
  namespace: projectd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: projectd-front
  template:
    metadata:
      labels:
        app: projectd-front
    spec:
      containers:
      - name: projectd-front
        image: skreet2k/projectd-front:1.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
