kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: projectd-back
  namespace: projectd
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
