apiVersion: v1
kind: Service
metadata:
  name: projectd-back
  namespace: projectd
spec:
  selector:
    app: projectd-back
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30400
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: projectd-front
  namespace: projectd
spec:
  selector:
    app: projectd-front
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30410
      name: http
