name: Publish Docker image to Docker Hub

on:
  release:
    types: [published]

jobs:
  push_to_back_registry:
    name: Deploy Back
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: skreet2k/projectd-back
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./back/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push_to_front_registry:
    name: Deploy Front
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: skreet2k/projectd-front
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./front/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  edit_docker_version_back:
    name: Modifiy repository files
    needs: [push_to_back_registry, push_to_front_registry]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - name: Modifiy the specific files using scripts
        run: |
         sed -E -i 's!skreet2k\/projectd-back:.+!skreet2k\/projectd-back:${{ github.event.release.tag_name }}!g' kustomization/deployment.yaml
         sed -E -i 's!skreet2k\/projectd-front:.+!skreet2k\/projectd-front:${{ github.event.release.tag_name }}!g' kustomization/deployment.yaml
      - name: Commit and push changes
        run: |
          git add -A
          git commit -m "commit message"
          git push origin HEAD:main

